[workspace]
resolver = "2"
members = [
    "crates/horalix-dom",
    "crates/horalix-net",
    "crates/horalix-browser",
    "crates/horalix-cdp",
    "crates/horalix-js",
    "crates/horalix-cli",
    "src-tauri",
]

[workspace.package]
version = "3.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Kerim-Sabic/horalixweb"

[workspace.dependencies]
horalix-dom = { path = "crates/horalix-dom" }
horalix-net = { path = "crates/horalix-net" }
horalix-browser = { path = "crates/horalix-browser" }
horalix-cdp = { path = "crates/horalix-cdp" }
horalix-js = { path = "crates/horalix-js" }

html5ever = "0.29"
markup5ever = "0.14"
selectors = "0.26"
servo_arc = "0.4"
cssparser = "0.34"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
reqwest = { version = "0.12", features = ["cookies", "gzip", "brotli", "deflate", "native-tls-vendored"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
thiserror = "2"
anyhow = "1"
base64 = "0.22"
